services:
  postgresql:
    image: 17.5
    container_name: spring_sec_asymmetric
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: spring_app_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5435:5432"
    restart: unless-stopped

volumes:
  postgres:

